### ISSUE TITLE
iOS push notification backend setup failing "no such file or directory, open 'cert.pem'" I am using .p8 file

### ISSUE THREAD

**Issue by kaushalmahi12** [parse-community/Parse-SDK-iOS-OSX#1377]
when i am setting up the backend configuration for iOS it is failing

`ios: {
      pfx: process.env.DOT_P8_FILE_PATH,
      topic: 'xxxxxxxx',
      production: (process.env.NODE_ENV === 'production'),
    },`

it is complaining about "cert.pem" the exact statements are as follows

`          throw _iteratorError;
Error: ENOENT: no such file or directory, open 'cert.pem'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at resolveCredential (/Users/kaushalmahi/project/github/kaushalmahi12/healloApi/node_modules/apn/lib/credentials/resolve.js:16:15)
    at loadCredentials (/Users/kaushalmahi/project/github/kaushalmahi12/healloApi/node_modules/apn/lib/credentials/certificate/load.js:12:16)
    at loadAndValidate (/Users/kaushalmahi/project/github/kaushalmahi12/healloApi/node_modules/apn/lib/credentials/certificate/prepare.js:11:20)
`

**Comment by brianyyz** [comment]
The error seems pretty clear - the server isn't finding your certificate file (ENOENT). What is the content of the environment variable? What server are you running on?
