### ISSUE TITLE
PFUser.logInWithAuthType Uncaught internal server error

### ISSUE THREAD

**Issue by sami79031** [parse-community/Parse-SDK-iOS-OSX#1456]
I'm trying to authenticate user with Google using PFUser.logInWithAuthType.

```
var authData = [String: String]()
authData["id_token"] = googleUser.authentication.idToken
authData["id"] = googleUser.userID
PFUser.logInWithAuthType(inBackground: "google", authData: authData)

```
I have used this api in Parse Server Version 2.3.3 and just confirmed that it's all working well.
In the current app which is Parse Version 3.0 I get this error:

```
Uncaught internal server error. TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
    at write_ (_http_outgoing.js:603:11)
    at ClientRequest.write (_http_outgoing.js:575:10)
    at Promise (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:36:9)
    at new Promise (/opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:177:7)
    at Object.request (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:33:10)
    at googleRequest (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:47:23)
    at validateIdToken (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:8:10)
    at Object.validateAuthData (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:28:12)
    at /opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/index.js:56:20
    at Object.keys.map.provider (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:261:12)
    at Array.map (<anonymous>)
    at RestWrite.handleAuthDataValidation (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:253:45)
    at findUsersWithAuthData.then.r (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:382:17)
    at run (/opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:75:22)
    at /opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:92:30
    at flush (/opt/app-root/src/node_modules/core-js/library/modules/_microtask.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:61:11) TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
    at write_ (_http_outgoing.js:603:11)
    at ClientRequest.write (_http_outgoing.js:575:10)
    at Promise (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:36:9)
    at new Promise (/opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:177:7)
    at Object.request (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/httpsRequest.js:33:10)
    at googleRequest (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:47:23)
    at validateIdToken (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:8:10)
    at Object.validateAuthData (/opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/google.js:28:12)
    at /opt/app-root/src/node_modules/parse-server/lib/Adapters/Auth/index.js:56:20
    at Object.keys.map.provider (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:261:12)
    at Array.map (<anonymous>)
    at RestWrite.handleAuthDataValidation (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:253:45)
    at findUsersWithAuthData.then.r (/opt/app-root/src/node_modules/parse-server/lib/RestWrite.js:382:17)
    at run (/opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:75:22)
    at /opt/app-root/src/node_modules/core-js/library/modules/es6.promise.js:92:30
    at flush (/opt/app-root/src/node_modules/core-js/library/modules/_microtask.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by sami79031** [comment]
Update:
After changing Parse Server Version from 3.0 to 3.1.3 fixed the problem.
Sorry for the inconvenience but hope that will help others that have hit the same problem.
Closing the issue.

**Comment by drdaz** [comment]
Thanks for updating this. And I'm glad you figured it out 🙂

**Comment by LilMoke** [comment]
First I apologize for asking this here, but it is somewhat related and I have looked but cannot find where to get an answer.

I Have been using Parse for a few years and now have a need to add google login.

I have found a ParseGoogleUtils for Android.  Is there such a lib for iOS.

More importantly I upgraded to the latest Parse SDK and I am trying to find out the latest best easiest way to add Google Login.

Can someone here please help, or point me in a direction to go?
